package nextgenpos;

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class UI extends javax.swing.JFrame {
    private static int id = 0;
    private SaleConduct s;
    public static int rowCount = 0;
    private PricingStrategyForm pf;
    public static int active_strategy = 0;
   
    public UI() {
        initComponents();
    }
    
    public void addToTable(SalesLineItem sli){
        String id = sli.getProduct().getId();   
        String name = sli.getProduct().getName();
        int quantity = sli.getQuantity();
        double subTotal = sli.getSubTotal();
        sales_line_items_table.setValueAt(id, UI.rowCount, 0);
        sales_line_items_table.setValueAt(name, UI.rowCount, 1);
        sales_line_items_table.setValueAt(quantity, UI.rowCount, 2);
        sales_line_items_table.setValueAt(subTotal, UI.rowCount, 3);
        UI.rowCount += 1;
        total.setText(Double.toString(this.s.getTotal()));
    }
    
    public void deleteFromTable(int row){
        
        for(int col = 0; col < 4; col++){
            sales_line_items_table.setValueAt("", row, col);
        }
        
        //UI.rowCount -= 1;
        total.setText(Double.toString(this.s.getTotal()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        product_menu_add_form = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        product_menu_add_form_name = new javax.swing.JTextField();
        product_menu_add_form_brand = new javax.swing.JTextField();
        product_menu_add_form_quantity = new javax.swing.JTextField();
        product_menu_add_form_price = new javax.swing.JTextField();
        product_menu_add_form_add = new javax.swing.JButton();
        product_menu_add_form_done = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        sales_line_items_table = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        total = new javax.swing.JTextField();
        total_after_discount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        discount_amount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        id_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        qty_field = new javax.swing.JTextField();
        add_button = new javax.swing.JButton();
        discard_button = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        new_button = new javax.swing.JButton();
        finish_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        Strategy = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        product_menu = new javax.swing.JMenu();
        product_menu_add = new javax.swing.JMenuItem();
        product_menu_edit = new javax.swing.JMenuItem();

        product_menu_add_form.setTitle("Add Product");
        product_menu_add_form.setBounds(new java.awt.Rectangle(0, 0, 390, 350));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Name");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Brand");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Quantity");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Price");

        product_menu_add_form_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nextgenpos/add_small.png"))); // NOI18N
        product_menu_add_form_add.setText("Add");
        product_menu_add_form_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_menu_add_form_addActionPerformed(evt);
            }
        });

        product_menu_add_form_done.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nextgenpos/checked.gif"))); // NOI18N
        product_menu_add_form_done.setText("Done");
        product_menu_add_form_done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_menu_add_form_doneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(product_menu_add_form_name)
                    .addComponent(product_menu_add_form_brand)
                    .addComponent(product_menu_add_form_quantity)
                    .addComponent(product_menu_add_form_price)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(product_menu_add_form_add, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(product_menu_add_form_done, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(product_menu_add_form_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(product_menu_add_form_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(product_menu_add_form_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(product_menu_add_form_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(product_menu_add_form_add)
                    .addComponent(product_menu_add_form_done))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nextgenpos/new_product.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout product_menu_add_formLayout = new javax.swing.GroupLayout(product_menu_add_form.getContentPane());
        product_menu_add_form.getContentPane().setLayout(product_menu_add_formLayout);
        product_menu_add_formLayout.setHorizontalGroup(
            product_menu_add_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, product_menu_add_formLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        product_menu_add_formLayout.setVerticalGroup(
            product_menu_add_formLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NextGenPOS");

        sales_line_items_table.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        sales_line_items_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Quantity", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(sales_line_items_table);

        total.setEditable(false);
        total.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        total.setText("0.0");

        total_after_discount.setEditable(false);
        total_after_discount.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        total_after_discount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        total_after_discount.setText("0.0");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Total");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Total after Discount");

        discount_amount.setEditable(false);
        discount_amount.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        discount_amount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        discount_amount.setText("0.0");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Discount");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(discount_amount)
                    .addComponent(total_after_discount)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_after_discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(discount_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product", 0, 0, new java.awt.Font("Courier New", 0, 18))); // NOI18N

        id_field.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        id_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        id_field.setToolTipText("");
        id_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("ID");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Qty");

        qty_field.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        qty_field.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        qty_field.setToolTipText("");
        qty_field.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        add_button.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nextgenpos/add.png"))); // NOI18N
        add_button.setToolTipText("Add");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        discard_button.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        discard_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nextgenpos/discard.png"))); // NOI18N
        discard_button.setToolTipText("Discard");
        discard_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discard_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(id_field, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(qty_field, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(discard_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(id_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(qty_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_button)
                .addGap(18, 18, 18)
                .addComponent(discard_button))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sale", 0, 0, new java.awt.Font("Courier New", 0, 18))); // NOI18N

        new_button.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        new_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nextgenpos/new.png"))); // NOI18N
        new_button.setToolTipText("New Sale");
        new_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_buttonActionPerformed(evt);
            }
        });

        finish_button.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        finish_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nextgenpos/finish.png"))); // NOI18N
        finish_button.setToolTipText("Finish Current Sale");
        finish_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finish_buttonActionPerformed(evt);
            }
        });

        cancel_button.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cancel_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nextgenpos/cancel.png"))); // NOI18N
        cancel_button.setToolTipText("Cancel Current Sale");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(new_button, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(finish_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cancel_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(new_button)
                .addGap(18, 18, 18)
                .addComponent(finish_button, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancel_button)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        Menu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menu.setText("Menu");
        menu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Strategy.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Strategy.setText("Pricing Strategy");
        Strategy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StrategyActionPerformed(evt);
            }
        });
        menu.add(Strategy);

        Exit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Exit.setText("Exit");
        Exit.setPreferredSize(new java.awt.Dimension(90, 22));
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        menu.add(Exit);

        Menu.add(menu);

        product_menu.setText("Product");
        product_menu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        product_menu_add.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        product_menu_add.setText("Add");
        product_menu_add.setPreferredSize(new java.awt.Dimension(127, 22));
        product_menu_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_menu_addActionPerformed(evt);
            }
        });
        product_menu.add(product_menu_add);

        product_menu_edit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        product_menu_edit.setText("Edit");
        product_menu.add(product_menu_edit);

        Menu.add(product_menu);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* finish current sale and display total */
    private void finish_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finish_buttonActionPerformed
        double t = 0 ;
        
        try{
            if(UI.active_strategy == 0){        /* no pricing strategy */
                t = this.s.getTotal();
            }
            
            else if(UI.active_strategy == 1){   /* percentage discount strategy */
                PercentDiscountPricingStrategy obj = new PercentDiscountPricingStrategy(pf.getPercent());
                t = obj.getTotal(this.s);
            }
            
            else if(UI.active_strategy == 2){   /* threshold discount strategy */
                AbsoluteDiscountOverThresholdPricingStrategy obj = new AbsoluteDiscountOverThresholdPricingStrategy(pf.getDiscount(), pf.getThreshold());
                t = obj.getTotal(this.s);
            }
            
            total_after_discount.setText(Double.toString(t));
            double discount = Double.parseDouble(total.getText()) -Double.parseDouble(total_after_discount.getText());
            discount_amount.setText(Double.toString(discount));
            this.s.setTotal(t);
            Database db = new Database("root", "");
            db.saveSale(this.s);
            this.s = null;
        } catch(NullPointerException npe){
            System.out.println("Cannot finish sale that has not been started!");
        }
        
        this.pf = null;
        this.clearTable();
        this.clearInputFields();
    }//GEN-LAST:event_finish_buttonActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    /* Sale -> New */
    private void new_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_buttonActionPerformed
        s = new SaleConduct(UI.id);            /* start new sale */
        UI.id += 1;
        total.setText("0.0");
        this.clearInputFields();
        //Product.initializeProducts();   /* generate product list */
        Database db = new Database("root", "");
        db.getProducts();
    }//GEN-LAST:event_new_buttonActionPerformed

    private void clearInputFields(){
        id_field.setText("");
        qty_field.setText("");
    }
    
    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
        s = null;   /* destroy sale object */
        total.setText("0.0");
        this.clearTable();
        this.clearInputFields();
    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void clearTable(){
        for(int i=0; i< UI.rowCount; i++)
            for(int j=0; j<4; j++)
                sales_line_items_table.setValueAt("", i, j);
        
        UI.rowCount = 0;
    }
    
    /* Product -> Discard */
    private void discard_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discard_buttonActionPerformed
        // get selected row
        int row = sales_line_items_table.getSelectedRow();
        // get product id of selection
        String id = sales_line_items_table.getValueAt(row, 0).toString();
        // delete curresponding sales line item
        s.deleteFromSalesLineItemList(id);
        // update table
        this.deleteFromTable(row);
    }//GEN-LAST:event_discard_buttonActionPerformed

    /* Product -> Add */
    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        if(this.s == null){
            System.out.println("Cannot add items without starting a new sale!");
            return;
        }
        
        String id = id_field.getText();
        String q = qty_field.getText();
        int qty = 0;
        
        try{
            qty = Integer.parseInt(q);
        } catch(NumberFormatException nfe){
            System.out.println(nfe.getMessage());
        } catch(NullPointerException npe){
            System.out.println(npe.getMessage());
        }
        
        Product temp = Product.findProduct(id);
        SalesLineItem sli = null;
        
        try{
            sli = new SalesLineItem(this.s, temp, qty);
        } catch(NullPointerException npe){
            System.out.println(npe.getMessage());
        }
        
        this.addToTable(sli);
    }//GEN-LAST:event_add_buttonActionPerformed

    private void StrategyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StrategyActionPerformed
        UI.active_strategy = 0;
        pf = new PricingStrategyForm();
        pf.setLocationRelativeTo(null);
        pf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        pf.setVisible(true);
    }//GEN-LAST:event_StrategyActionPerformed

    private void product_menu_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_menu_addActionPerformed
        //this.setVisible(false);
        product_menu_add_form.setLocationRelativeTo(null);
        product_menu_add_form.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        product_menu_add_form.setVisible(true);
    }//GEN-LAST:event_product_menu_addActionPerformed

    private void product_menu_add_form_doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_menu_add_form_doneActionPerformed
        product_menu_add_form.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_product_menu_add_form_doneActionPerformed

    private void product_menu_add_form_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_menu_add_form_addActionPerformed
        try{
          Database db = new Database("root", "");
          db.addProduct(new Product("", product_menu_add_form_name.getText(), product_menu_add_form_brand.getText(), Integer.parseInt(product_menu_add_form_quantity.getText()), Double.parseDouble(product_menu_add_form_price.getText())));
          product_menu_add_form_name.setText(null);
          product_menu_add_form_brand.setText(null);
          product_menu_add_form_quantity.setText(null);
          product_menu_add_form_price.setText(null);
        } catch(NullPointerException npe){
            System.out.println(npe.getMessage());
        }
    }//GEN-LAST:event_product_menu_add_form_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem Strategy;
    private javax.swing.JButton add_button;
    private javax.swing.JButton cancel_button;
    private javax.swing.JButton discard_button;
    private javax.swing.JTextField discount_amount;
    private javax.swing.JButton finish_button;
    private javax.swing.JTextField id_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu menu;
    private javax.swing.JButton new_button;
    private javax.swing.JMenu product_menu;
    private javax.swing.JMenuItem product_menu_add;
    private javax.swing.JFrame product_menu_add_form;
    private javax.swing.JButton product_menu_add_form_add;
    private javax.swing.JTextField product_menu_add_form_brand;
    private javax.swing.JButton product_menu_add_form_done;
    private javax.swing.JTextField product_menu_add_form_name;
    private javax.swing.JTextField product_menu_add_form_price;
    private javax.swing.JTextField product_menu_add_form_quantity;
    private javax.swing.JMenuItem product_menu_edit;
    private javax.swing.JTextField qty_field;
    private javax.swing.JTable sales_line_items_table;
    private javax.swing.JTextField total;
    private javax.swing.JTextField total_after_discount;
    // End of variables declaration//GEN-END:variables
}